## Упражнения по библиотеке Numpy

In [7]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
import numpy as np
arr = np.random.randint(-10, 11, size=15)
filter = (arr >= 3) & (arr <= 8)
arr[filter] *= -1

**2.** Заменить максимальный элемент случайного массива на 0

In [9]:
import numpy as np
arr = np.random.randint(1, 11, size=15)
arr[np.max(arr)] = 0

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [10]:
# your code
import numpy as np
from itertools import product
def my_func(arr: np.ndarray):
    lists = arr.tolist()
    result = list(product(*lists))
    return np.array(result)

a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(my_func(a))

[[1 3 5]
 [1 3 6]
 [1 4 5]
 [1 4 6]
 [2 3 5]
 [2 3 6]
 [2 4 5]
 [2 4 6]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [11]:
# your code
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [2, 3, 5],
    [5, 7, 9],
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9]
])

B = np.array([
    [2, 3],
    [3, 5]
])

mask = np.ones(len(A), dtype=bool)
for b_row in B:
    contains = np.array([np.isin(b_row, row).all() for row in A])
    mask &= contains

result = A[mask]
print(result)

[[2 3 5]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [12]:
# your code
import numpy as np

A = np.array([
    [1, 2, 3],
    [3, 3, 3],
    [4, 5, 6],
    [7, 7, 7],
    [1, 1, 2],
    [2, 2, 2],
    [0, 1, 0],
    [5, 5, 5],
    [9, 8, 7],
    [3, 4, 3]
])

filteredA = A[~np.all(A == A[:,0][:,None], axis=1)]
print(filteredA)

[[1 2 3]
 [4 5 6]
 [1 1 2]
 [0 1 0]
 [9 8 7]
 [3 4 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [13]:
# your code
import numpy as np

A = np.array([
    [1, 2, 3],
    [3, 3, 3],
    [1, 2, 3],
    [4, 5, 6],
    [3, 3, 3],
    [7, 8, 9]
])

unique = np.unique(A, axis=0)
print(unique)

[[1 2 3]
 [3 3 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [14]:
# your code
def diag_matrix_first(X):
    n = min(len(X), len(X[0]))
    prod = 1
    for i in range(n):
        if X[i][i] != 0:
            prod *= X[i][i]
    return prod

import numpy as np

def diag_matrix_numpy(X):
    diag = np.diag(X)
    return np.prod(diag[diag != 0])

X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(diag_matrix_first(X))
print(diag_matrix_numpy(X))

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [15]:
# your code
def f_without_numpy(x, y):
    return sorted(x) == sorted(y)

import numpy as np

def f_with_numpy(x, y):
    return np.array_equal(np.sort(x), np.sort(y))

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
print(f_without_numpy(x,y))
print(f_with_numpy(x,y))

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [28]:
# your code

def my_func(x):
    arr=[]
    for i in range(1, len(x)):
        if x[i-1] == 0:
            arr.append(x[i])
    return max(arr)

import numpy as np
def my_fuc_numpy(x):
    return np.max(x[1:][x[:-1] == 0])

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(my_func(x))
print(my_fuc_numpy(x))

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [32]:
# your code
def my_func(x):
    values, counts = [], []
    prev_value = x[0]
    count = 1
    for i in x[1:]:
        if i == prev_value:
            count += 1
        else:
            values.append(prev_value)
            counts.append(count)
            prev_value, count = i, 1
    values.append(prev_value)
    counts.append(count)
    return values, counts

import numpy as np
def my_fuc_numpy(x):
    index = np.flatnonzero(np.diff(x)) + 1
    return x[np.r_[0, index]], np.diff(np.r_[0, index, len(x)])

x = np.array([2, 2, 2, 3, 3, 3, 5])
print(my_func(list(x)))
print(my_fuc_numpy(x))

([np.int64(2), np.int64(3), np.int64(5)], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [35]:
# your code
import math

def my_func(X, Y):
    x, y = len(X), len(Y)
    result = [[0.0] * y for _ in range(x)]
    for i in range(x):
        for j in range(y):
            s = 0
            for k in range(len(X[0])):
                diff = X[i][k] - Y[j][k]
                s += diff * diff
            result[i][j] = math.sqrt(s)
    return result

import numpy as np

def my_func_numpy(X, Y):
    x = np.sum(X**2, axis=1)[:, None]
    y = np.sum(Y**2, axis=1)[None, :]
    return np.sqrt(x + y - 2 * X @ Y.T)

X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8], [9, 10]])
print(my_func(X.tolist(), Y.tolist()))
print(my_func_numpy(X, Y))

from scipy.spatial.distance import cdist
import time

X = np.random.randn(1000, 50)
Y = np.random.randn(800, 50)

time_1 = time.time()
my_func(X.tolist(), Y.tolist())
print("NoNumPy:", time.time() - time_1)

time_2 = time.time()
my_func_numpy(X, Y)
print("NumPy:", time.time() - time_2)

time_3 = time.time()
cdist(X, Y)
print("scipy:", time.time() - time_3)

[[5.656854249492381, 8.48528137423857, 11.313708498984761], [2.8284271247461903, 5.656854249492381, 8.48528137423857]]
[[ 5.65685425  8.48528137 11.3137085 ]
 [ 2.82842712  5.65685425  8.48528137]]
NoNumPy: 4.467429876327515
NumPy: 0.025986671447753906
scipy: 0.022806882858276367


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [19]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [8]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:
# your code
average_calories = np.average(calorie_stats) - 60
print(average_calories)

46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [7]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [6]:
# your code
median_calories = np.median(calorie_stats_sorted)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [10]:
# your code
for i in range(0, 101):
    value = np.percentile(calorie_stats_sorted, i)
    print(f"{i} procentile: {value}")
    if value > 60:
        nth_percentile = i
        break
print(f"min procentile: {nth_percentile}")

0 procentile: 50.0
1 procentile: 50.0
2 procentile: 50.0
3 procentile: 55.599999999999994
4 procentile: 70.0
min procentile: 4


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [12]:
# your code
more_calories = np.mean(np.array(calorie_stats_sorted) > 60) * 100
print(more_calories, "%")

96.1038961038961 %


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [13]:
# your code
calorie_std = np.std(calorie_stats_sorted)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [15]:
# your code
"""На основании анализа можно заметить, что у большей части конкурирующих хлопьев калорийность на порцию превышает 60 калорий,
и в среднем они имеют ещё более высокое значение. При этом стандартное отклонение показывает заметный разброс значений, 
то есть часть конкурентов делает более калорийные продукты. 
Для Mycrunch это можно использовать как маркетинговое преимущество: подчеркнуть, что продукт содержит меньше калорий, 
чем большинство альтернатив на рынке, и позиционировать его как более лёгкий и полезный продукт."""

'На основании анализа можно заметить, что у большей части конкурирующих хлопьев калорийность на порцию превышает 60 калорий,\nи в среднем они имеют ещё более высокое значение. При этом стандартное отклонение показывает заметный разброс значений, \nто есть часть конкурентов делает более калорийные продукты. \nДля Mycrunch это можно использовать как маркетинговое преимущество: подчеркнуть, что продукт содержит меньше калорий, \nчем большинство альтернатив на рынке, и позиционировать его как более лёгкий и полезный продукт.'